[project]
name = "4ma-locator-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.18.0",
    "pydantic>=2.12.3",
    "python-levenshtein>=0.27.1",
    "rapidfuzz>=3.14.1",
]
